name: Hello World CI/CD

on:
  push:
    branches: [ master ]

jobs:
  deploy-and-email:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install dependencies
        run: npm install

      - name: Deploy to Windows via SSH
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.LOCAL_HOST }}
          username: ${{ secrets.LOCAL_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          port: 22
          script: |
            powershell.exe -Command "
              cd 'C:\html-cicd-test';
              git pull origin master;
            "

      - name: Send email notification
        if: always()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USER }}
          password: ${{ secrets.EMAIL_PASS }}
          subject: Hello World Deploy Notification
          to: panjiyar17251@gmail.com
          from: CI Bot <${{ secrets.EMAIL_USER }}>
          body: |
            Hello,

            Your "Hello World" project has been deployed to the Windows server.

            ✅ Deployment Successful!
