name: Developer Pipeline

on:
  push:
    branches:
      - master

jobs:
  sonarcloud:
    name: SonarCloud Analysis
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Run SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        with:
          organization: your_organization
          projectKey: your_project_key
          token: ${{ secrets.SONAR_TOKEN }}

  trigger-tester-repo:
    name: Trigger Tester Repo
    needs: sonarcloud
    runs-on: ubuntu-latest
    if: success()

    steps:
      - name: Simulate Build
        run: echo "Static site build done"

      - name: Trigger Tester Repo Workflow
        run: |
          curl -X POST https://api.github.com/repos/Indra512/PlaywrightCucumberTypeScript/dispatches \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: token ${{ secrets.TEST_REPO_PAT }}" \
          -d '{"event_type":"dev-completed"}'
