name: SonarQube Scan

on:
  push:
    branches: [ master ]

jobs:
  sonarqube:
    name: SonarQube Analysis
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Java (needed by SonarScanner)
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Install SonarScanner CLI
      run: npm install -g sonarqube-scanner

    - name: Run SonarScanner
      env:
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
      run: |
        # Use default SonarQube URL if SONAR_HOST_URL is empty
        if [ -z "$SONAR_HOST_URL" ]; then
          SONAR_HOST_URL="http://localhost:9000"
        fi

        sonar-scanner \
          -Dsonar.token=$SONAR_TOKEN \
          -Dsonar.host.url=$SONAR_HOST_URL
